### ISSUE TITLE
Terminology (positive vs. nonnegative)

### ISSUE THREAD

**Issue by danhales** [learn-co-curriculum/dsc-intro-to-probability#2]
- The number of text messages you send each day:  in this case, S is equal to some number x, with x being a **positive integer**, or mathematically: $S = \{x \mid x \in \mathbb{Z}, x \geq 0\}$

This line defines a set of nonnegative integers, but says S consists of positive integers

**Comment by hoffm386** [comment]
This is updated in the latest version, with additional clarification of what each part of the set definition is doing. Thanks for flagging @danhales!
